#!/usr/bin/env python
"""Prepare an isolated v9c label workspace for hack-day collaboration.

This script only reads existing repo artifacts and writes into
hackday/v9c_label_prep/generated by default.  It does not mutate data/, src/,
models/, reports/, or jobs/.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any

import pandas as pd


CLASSES = ("snia", "nonIa_snlike", "other")
ALLOWED_QUALITY = {"spectroscopic", "strong", "consensus", "weak", "context"}


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def read_table(path: Path, columns: list[str] | None = None) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    if path.suffix.lower() == ".parquet":
        return pd.read_parquet(path, columns=columns)
    return pd.read_csv(path, usecols=columns)


def lightcurve_path(root: Path, object_id: str) -> str:
    candidates = [
        root / f"{object_id}.json",
        root / f"{object_id}.parquet",
        root / "dp1" / f"{object_id}.parquet",
        root / "dp1" / f"{object_id}.json",
    ]
    for path in candidates:
        if path.exists():
            return str(path.relative_to(repo_root()))
    return ""


def load_split(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    payload = json.loads(path.read_text())
    if "split" in payload and isinstance(payload["split"], dict):
        payload = payload["split"]
    out: dict[str, str] = {}
    for name, keys in {
        "train": ("train_ids", "train"),
        "cal": ("cal_ids", "cal"),
        "test": ("test_ids", "test"),
    }.items():
        for key in keys:
            for oid in payload.get(key, []) or []:
                out[str(oid)] = name
    return out


def normalize_class(value: Any) -> tuple[str | None, str]:
    raw = "" if value is None or (isinstance(value, float) and math.isnan(value)) else str(value).strip()
    low = raw.lower().replace("-", " ").replace("_", " ")
    low = " ".join(low.split())
    aliases = {
        "snia": "snia",
        "ia": "snia",
        "sn ia": "snia",
        "type ia": "snia",
        "nonia": "nonIa_snlike",
        "non ia": "nonIa_snlike",
        "nonia snlike": "nonIa_snlike",
        "non ia snlike": "nonIa_snlike",
        "noniasnlike": "nonIa_snlike",
        "sn ii": "nonIa_snlike",
        "sn iib": "nonIa_snlike",
        "sn iin": "nonIa_snlike",
        "sn ib": "nonIa_snlike",
        "sn ic": "nonIa_snlike",
        "sn ibc": "nonIa_snlike",
        "slsn": "nonIa_snlike",
        "other": "other",
        "agn": "other",
        "qso": "other",
        "vs": "other",
        "variable": "other",
        "star": "other",
        "asteroid": "other",
        "bogus": "other",
    }
    if raw in CLASSES:
        return raw, ""
    if low in aliases:
        return aliases[low], ""
    if low.startswith("sn ia"):
        return "snia", ""
    if low.startswith(("sn ii", "sn ib", "sn ic")):
        return "nonIa_snlike", ""
    if low == "sn":
        return None, "generic SN is not a final ternary label"
    return None, f"unknown class {raw!r}"


def object_inventory(root: Path, out_dir: Path, split_map: dict[str, str]) -> pd.DataFrame:
    snap_path = root / "data/gold/object_epoch_snapshots_fusion_v9c.parquet"
    if not snap_path.exists():
        return pd.DataFrame()
    cols = ["object_id", "n_det", "survey", "target_class", "label_quality", "label_source"]
    snap = read_table(snap_path, columns=cols)
    grouped = snap.groupby("object_id", dropna=False)
    inv = grouped.agg(
        n_epoch_rows=("n_det", "size"),
        max_n_det=("n_det", "max"),
        survey=("survey", "first"),
        target_class=("target_class", "first"),
        label_quality=("label_quality", "first"),
        label_source=("label_source", "first"),
    ).reset_index()
    inv["object_id"] = inv["object_id"].astype(str)
    inv["split"] = inv["object_id"].map(split_map).fillna("new_or_unsplit")
    inv["lightcurve_path"] = inv["object_id"].map(lambda oid: lightcurve_path(root / "data/lightcurves", oid))
    inv["has_lightcurve"] = inv["lightcurve_path"].astype(bool)

    seq_path = root / "data/silver/local_expert_outputs/seq_v9/part-latest.parquet"
    if seq_path.exists():
        seq = read_table(seq_path, columns=["object_id", "available"])
        seq["object_id"] = seq["object_id"].astype(str)
        seq_counts = seq.groupby("object_id").agg(
            seq_v9_epoch_rows=("available", "size"),
            seq_v9_available_epochs=("available", "sum"),
        ).reset_index()
        inv = inv.merge(seq_counts, on="object_id", how="left")
    else:
        inv["seq_v9_epoch_rows"] = 0
        inv["seq_v9_available_epochs"] = 0
    inv[["seq_v9_epoch_rows", "seq_v9_available_epochs"]] = inv[
        ["seq_v9_epoch_rows", "seq_v9_available_epochs"]
    ].fillna(0).astype(int)

    pred_path = root / "data/scores/predictions_fusion_v9c.parquet"
    if pred_path.exists():
        pred_cols = ["object_id", "n_det", "p_snia", "p_nonia", "p_other", "p_follow_proxy"]
        pred = read_table(pred_path, columns=pred_cols)
        pred["object_id"] = pred["object_id"].astype(str)
        pred5 = pred[pred["n_det"] == 5].copy()
        if not pred5.empty:
            pred5["pred_class"] = pred5[["p_snia", "p_nonia", "p_other"]].idxmax(axis=1).str.replace("p_", "", regex=False)
            pred5["max_prob"] = pred5[["p_snia", "p_nonia", "p_other"]].max(axis=1)
            pred5["uncertainty"] = 1.0 - pred5["max_prob"]
            inv = inv.merge(
                pred5[["object_id", "p_snia", "p_nonia", "p_other", "p_follow_proxy", "pred_class", "max_prob", "uncertainty"]],
                on="object_id",
                how="left",
            )
    inv.to_csv(out_dir / "current_v9c_inventory.csv", index=False)
    return inv


def lsst_manifest(root: Path, out_dir: Path, inventory: pd.DataFrame) -> pd.DataFrame:
    path = root / "data/lsst_candidates.csv"
    if not path.exists():
        return pd.DataFrame()
    lsst = pd.read_csv(path)
    lsst["object_id"] = lsst["object_id"].astype(str)
    lsst["weak_target_class"] = lsst["alerce_stamp_class"].astype(str).str.upper().map(
        lambda s: "nonIa_snlike" if s == "SN" else "other"
    )
    lsst["lightcurve_path"] = lsst["object_id"].map(lambda oid: lightcurve_path(root / "data/lightcurves", oid))
    lsst["has_lightcurve_local"] = lsst["lightcurve_path"].astype(bool)
    in_v9c = set(inventory["object_id"].astype(str)) if not inventory.empty else set()
    lsst["in_local_v9c_snapshot"] = lsst["object_id"].isin(in_v9c)
    cols = [
        "object_id", "ra", "dec", "n_det", "alerce_stamp_class", "alerce_stamp_prob",
        "weak_target_class", "survey", "discovery_broker", "has_lightcurve_local",
        "in_local_v9c_snapshot", "lightcurve_path",
    ]
    lsst[cols].to_csv(out_dir / "lsst_candidates_manifest.csv", index=False)
    return lsst


def labeling_queue(out_dir: Path, inventory: pd.DataFrame, lsst: pd.DataFrame) -> pd.DataFrame:
    frames = []
    if not inventory.empty:
        q = inventory.copy()
        q["reason"] = ""
        q.loc[q["target_class"].isna(), "reason"] = "missing_target"
        q.loc[q["label_quality"].eq("bts_unclassified"), "reason"] = "bts_unclassified_demoted"
        q.loc[q["label_quality"].eq("weak") & q["reason"].eq(""), "reason"] = "weak_label_upgrade"
        if "uncertainty" in q.columns:
            q.loc[(q["label_quality"].eq("weak")) & (q["uncertainty"].fillna(0) > 0.35), "reason"] = "weak_label_high_uncertainty"
        q = q[q["reason"].ne("")]
        q["priority"] = q["reason"].map({
            "missing_target": 0,
            "bts_unclassified_demoted": 1,
            "weak_label_high_uncertainty": 2,
            "weak_label_upgrade": 3,
        }).fillna(9).astype(int)
        q["safe_for_training_update"] = q["split"].ne("test")
        frames.append(q)
    if not lsst.empty:
        l = lsst[~lsst["in_local_v9c_snapshot"]].copy()
        l["target_class"] = l["weak_target_class"]
        l["label_quality"] = "weak"
        l["label_source"] = "alerce_stamp_lsst"
        l["split"] = "new_or_unsplit"
        l["max_n_det"] = l["n_det"]
        l["reason"] = "lsst_candidate_needs_lightcurve_or_stronger_label"
        l["priority"] = 4
        l["safe_for_training_update"] = True
        l = l.rename(columns={"has_lightcurve_local": "has_lightcurve"})
        frames.append(l)
    if not frames:
        out = pd.DataFrame()
    else:
        out = pd.concat(frames, ignore_index=True, sort=False)
        sort_cols = [c for c in ["priority", "safe_for_training_update", "uncertainty"] if c in out.columns]
        out = out.sort_values(sort_cols, ascending=[True, False, False][: len(sort_cols)])
    out.to_csv(out_dir / "labeling_queue.csv", index=False)
    return out


def normalize_incoming_labels(path: Path, root: Path, out_dir: Path, split_map: dict[str, str]) -> tuple[pd.DataFrame, pd.DataFrame]:
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "object_id,final_class_ternary,label_quality,label_source,final_class_raw,tns_name,redshift,ra,dec,source_ref,notes\n"
        )
    raw = pd.read_csv(path).fillna("")
    if raw.empty:
        audit = pd.DataFrame(columns=[
            "object_id", "valid", "action", "error", "existing_class", "existing_quality",
            "incoming_class", "incoming_quality", "incoming_source", "split", "has_lightcurve",
            "lightcurve_path", "safe_for_training_update",
        ])
        audit.to_csv(out_dir / "new_label_merge_plan.csv", index=False)
        truth = read_table(root / "data/truth/object_truth.parquet")
        truth.to_csv(out_dir / "object_truth_with_new_labels.csv", index=False)
        try:
            truth.to_parquet(out_dir / "object_truth_with_new_labels.parquet", index=False)
        except Exception as exc:
            (out_dir / "object_truth_with_new_labels.parquet.ERROR.txt").write_text(str(exc))
        labels = read_table(root / "data/labels.csv")
        labels.to_csv(out_dir / "labels_with_new_objects.csv", index=False)
        return raw, audit

    truth_path = root / "data/truth/object_truth.parquet"
    truth = read_table(truth_path)
    truth["object_id"] = truth["object_id"].astype(str)
    existing = truth.set_index("object_id", drop=False) if not truth.empty else pd.DataFrame().set_index(pd.Index([]))

    records = []
    seen: set[str] = set()
    for _, row in raw.iterrows():
        oid = str(row.get("object_id", "")).strip()
        cls_source = row.get("final_class_ternary") or row.get("target_class") or row.get("label")
        norm_cls, cls_error = normalize_class(cls_source)
        quality = str(row.get("label_quality", "") or "spectroscopic").strip()
        source = str(row.get("label_source", "") or "hackday_new_labels").strip()
        errors = []
        if not oid:
            errors.append("missing object_id")
        if oid in seen:
            errors.append("duplicate object_id in incoming file")
        seen.add(oid)
        if cls_error:
            errors.append(cls_error)
        if quality not in ALLOWED_QUALITY:
            errors.append(f"invalid label_quality {quality!r}")
        lc = lightcurve_path(root / "data/lightcurves", oid) if oid else ""
        old = existing.loc[oid] if oid in existing.index else {}
        old_class = old.get("final_class_ternary") if isinstance(old, pd.Series) else None
        old_quality = old.get("label_quality") if isinstance(old, pd.Series) else None
        valid = not errors
        action = "invalid"
        if valid:
            if oid in existing.index:
                action = "unchanged" if str(old_class) == str(norm_cls) and str(old_quality) == quality else "update"
            else:
                action = "insert"
        records.append({
            "object_id": oid,
            "valid": valid,
            "action": action,
            "error": "; ".join(errors),
            "existing_class": old_class,
            "existing_quality": old_quality,
            "incoming_class": norm_cls,
            "incoming_quality": quality,
            "incoming_source": source,
            "split": split_map.get(oid, "new_or_unsplit"),
            "has_lightcurve": bool(lc),
            "lightcurve_path": lc,
            "safe_for_training_update": valid and split_map.get(oid) != "test" and bool(lc),
        })

    audit = pd.DataFrame(records)
    audit.to_csv(out_dir / "new_label_merge_plan.csv", index=False)

    valid = audit[audit["valid"]].copy()
    if valid.empty:
        truth.to_csv(out_dir / "object_truth_with_new_labels.csv", index=False)
        try:
            truth.to_parquet(out_dir / "object_truth_with_new_labels.parquet", index=False)
        except Exception:
            pass
        return raw, audit

    additions = []
    raw_idx = raw.set_index(raw["object_id"].astype(str), drop=False)
    for _, plan in valid.iterrows():
        oid = str(plan["object_id"])
        row = raw_idx.loc[oid]
        final_raw = str(row.get("final_class_raw", "") or row.get("final_class_ternary", "") or plan["incoming_class"]).strip()
        additions.append({
            "object_id": oid,
            "final_class_ternary": plan["incoming_class"],
            "follow_proxy": int(plan["incoming_class"] == "snia"),
            "label_source": plan["incoming_source"],
            "label_quality": plan["incoming_quality"],
            "final_class_raw": final_raw,
            "tns_name": row.get("tns_name", ""),
            "redshift": row.get("redshift", ""),
            "truth_timestamp": None,
            "hackday_source_ref": row.get("source_ref", ""),
            "hackday_notes": row.get("notes", ""),
            "ra": row.get("ra", ""),
            "dec": row.get("dec", ""),
        })
    new_truth = pd.DataFrame(additions)
    merged = pd.concat([
        truth[~truth["object_id"].astype(str).isin(set(new_truth["object_id"].astype(str)))],
        new_truth,
    ], ignore_index=True, sort=False)
    merged.to_csv(out_dir / "object_truth_with_new_labels.csv", index=False)
    try:
        merged.to_parquet(out_dir / "object_truth_with_new_labels.parquet", index=False)
    except Exception as exc:
        (out_dir / "object_truth_with_new_labels.parquet.ERROR.txt").write_text(str(exc))

    labels = read_table(root / "data/labels.csv")
    if labels.empty:
        labels = pd.DataFrame(columns=["object_id", "label", "ra", "dec", "survey", "n_det", "discovery_broker"])
    labels["object_id"] = labels["object_id"].astype(str)
    present = set(labels["object_id"])
    new_label_rows = []
    for _, add in new_truth.iterrows():
        if add["object_id"] in present:
            continue
        new_label_rows.append({
            "object_id": add["object_id"],
            "label": add["final_class_ternary"],
            "ra": add.get("ra", ""),
            "dec": add.get("dec", ""),
            "survey": "LSST" if str(add["object_id"]).isdigit() else "ZTF",
            "n_det": "",
            "discovery_broker": add.get("label_source", "hackday_new_labels"),
        })
    labels_out = pd.concat([labels, pd.DataFrame(new_label_rows)], ignore_index=True, sort=False)
    labels_out.to_csv(out_dir / "labels_with_new_objects.csv", index=False)
    return raw, audit


def write_summary(root: Path, out_dir: Path, inventory: pd.DataFrame, lsst: pd.DataFrame, audit: pd.DataFrame) -> None:
    def value_counts(df: pd.DataFrame, col: str) -> dict[str, int]:
        if df.empty or col not in df:
            return {}
        return {str(k): int(v) for k, v in df[col].value_counts(dropna=False).items()}

    metrics_path = root / "reports/metrics/fusion_v9c_train.json"
    metrics = json.loads(metrics_path.read_text()) if metrics_path.exists() else {}
    gates = metrics.get("component_gates", metrics.get("gates", [])) if isinstance(metrics, dict) else []
    seq_gate = next((g for g in gates if isinstance(g, dict) and g.get("component") == "seq_v9_expert"), None)
    stage_a_seq = (((metrics.get("stage_a") or {}).get("metrics") or {}).get("seq_v9") if metrics else None)

    summary = {
        "workspace": str(out_dir.relative_to(root)),
        "local_v9c": {
            "n_objects": int(len(inventory)) if not inventory.empty else 0,
            "survey_counts": value_counts(inventory, "survey"),
            "class_counts": value_counts(inventory, "target_class"),
            "label_quality_counts": value_counts(inventory, "label_quality"),
            "seq_v9_stage_a": stage_a_seq,
            "seq_v9_gate": seq_gate,
        },
        "lsst_candidates": {
            "n_rows": int(len(lsst)) if not lsst.empty else 0,
            "stamp_class_counts": value_counts(lsst, "alerce_stamp_class"),
            "n_with_local_lightcurve": int(lsst["has_lightcurve_local"].sum()) if not lsst.empty else 0,
            "n_in_local_v9c_snapshot": int(lsst["in_local_v9c_snapshot"].sum()) if not lsst.empty else 0,
        },
        "incoming_labels": {
            "n_rows": int(len(audit)) if not audit.empty else 0,
            "valid": int(audit["valid"].sum()) if not audit.empty and "valid" in audit else 0,
            "actions": value_counts(audit, "action"),
            "safe_for_training_update": int(audit["safe_for_training_update"].sum()) if not audit.empty and "safe_for_training_update" in audit else 0,
        },
        "notes": [
            "This workspace is isolated; generated files are not used by live v9/v9c unless explicitly passed to pipeline commands.",
            "Local v9c snapshot is expected to be ZTF-only; SCC v9c is the LSST weak-label rebuild path.",
            "New labels for objects in the locked test split should be treated as audit truth unless the team deliberately re-registers a new split.",
        ],
    }
    (out_dir / "v9c_status_summary.json").write_text(json.dumps(summary, indent=2, default=str))

    lines = [
        "# v9c Prep Summary",
        "",
        f"- Local v9c objects: {summary['local_v9c']['n_objects']}",
        f"- Local survey counts: {summary['local_v9c']['survey_counts']}",
        f"- Local label quality counts: {summary['local_v9c']['label_quality_counts']}",
        f"- LSST candidates available locally: {summary['lsst_candidates']['n_rows']}",
        f"- LSST candidates with local lightcurves: {summary['lsst_candidates']['n_with_local_lightcurve']}",
        f"- Incoming label rows: {summary['incoming_labels']['n_rows']}",
        f"- Incoming valid rows: {summary['incoming_labels']['valid']}",
        "",
        "See `current_v9c_inventory.csv`, `labeling_queue.csv`, and `new_label_merge_plan.csv`.",
    ]
    (out_dir / "SUMMARY.md").write_text("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--new-labels", default="hackday/v9c_label_prep/incoming_new_labels.csv")
    parser.add_argument("--out-dir", default="hackday/v9c_label_prep/generated")
    args = parser.parse_args()

    root = repo_root()
    out_dir = root / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    split_map = load_split(root / "data/gold/split_fusion_v9c.json")
    inventory = object_inventory(root, out_dir, split_map)
    lsst = lsst_manifest(root, out_dir, inventory)
    labeling_queue(out_dir, inventory, lsst)
    _, audit = normalize_incoming_labels(root / args.new_labels, root, out_dir, split_map)
    write_summary(root, out_dir, inventory, lsst, audit)
    print(f"Wrote v9c hack-day prep artifacts to {out_dir}")


if __name__ == "__main__":
    main()
